"""
Django settings for EbbinghausAnywhere project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import environ


env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/


environ.Env.read_env( BASE_DIR / '.env')

SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = ['*']

# 显式读取 DEBUG(默认 False); local_settings 若有定义仍会覆盖此处
DEBUG = env('DEBUG', default=False)

# 实例角色: master(默认, 主库 = PythonAnywhere) / replica(副本, 如 NAS)。
# 仅用于安全守卫(sync/restore 命令只在 replica 上允许执行), 不改变主库任何行为。
EAW_ROLE = env('EAW_ROLE', default='master')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "EAW.apps.EawConfig",
    "api.apps.ApiConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# NAS 副本运行在容器内, 没有独立的静态文件服务, 由 WhiteNoise 直接从 Django 提供;
# 主库(PA)与本地开发不启用, 行为完全不变。
if EAW_ROLE == 'replica':
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = "EbbinghausAnywhere.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates',],  # 确保包含全局模板路径
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "EbbinghausAnywhere.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
#
# 默认值: 环境变量 DATABASE_URL(容器/NAS, 如 sqlite:////data/db.sqlite3),
# 否则本地 SQLite。文件末尾的 local_settings 导入可覆盖此处;
# 若显式设置了 DATABASE_URL, 则其优先级最高(见文件末尾)。
DATABASES = {
    'default': env.db('DATABASE_URL', default=f"sqlite:///{(BASE_DIR / 'db.sqlite3').as_posix()}"),
}

# NAS 同步配置(仅副本实例需要; 主库不设置这些变量)
EAW_SYNC_URL = env('EAW_SYNC_URL', default='')
EAW_SYNC_TOKEN = env('EAW_SYNC_TOKEN', default='')
EAW_SNAPSHOT_DIR = env('EAW_SNAPSHOT_DIR', default=str(BASE_DIR / 'snapshots'))




# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 静态文件的存放路径
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # 收集的静态文件最终存放路径

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # 默认认证后端
)

# REST API (供微信小程序与 NAS 同步使用)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'UNAUTHENTICATED_USER': None,
}

# 微信小程序(可选,不配置时仅微信登录端点不可用,其余功能不受影响)
WECHAT_APPID = env('WECHAT_APPID', default='')
WECHAT_SECRET = env('WECHAT_SECRET', default='')

# 登录和退出后的跳转路径
LOGIN_URL = '/accounts/login/'  # 用户未登录时，跳转的登录页面
LOGOUT_URL = 'home'  # 退出登录后跳转的页面
LOGIN_REDIRECT_URL = 'home'  # 登录成功后跳转的页面

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

try:
    from .local_settings import *
except ImportError:
    pass

# 显式设置 DATABASE_URL 时其优先级高于 local_settings(便于以环境变量切换数据库:
# NAS 容器部署、本地同步演练)。PA 的 .env 未设置该变量, 行为与之前完全一致。
if env('DATABASE_URL', default=''):
    DATABASES = {'default': env.db('DATABASE_URL')}
